[package]
name = "transaction-challenge"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1.6"
anyhow = "1.0.56"
serde = { version = "1.0.136", features = ["derive"] }
clap = { version = "3.1.6", features = ["derive"] }
insta = "1.13.0"